package core

import (
	"fmt"
	"github.com/pomelohq/pomelo/internal/agent/claude"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pomelohq/pomelo/internal/config"
)

const workspaceMapMarker = "<!-- pom:workspace-map -->"

func (s *Server) writeWorkspaceMap(branch string, isMain bool) {
	cfg := s.cfg()
	if cfg == nil || len(cfg.Repos) < 2 {
		return
	}
	root := s.workspaceRoot(branch, isMain)
	if root == "" {
		return
	}
	path := filepath.Join(root, "CLAUDE.md")
	if b, err := os.ReadFile(path); err == nil && !strings.Contains(string(b), workspaceMapMarker) {
		return
	}
	_ = os.WriteFile(path, []byte(buildWorkspaceMap(cfg, branch)), 0o644)
}

func buildWorkspaceMap(cfg *config.Config, branch string) string {
	order := cfg.RepoOrder
	if len(order) == 0 {
		for name := range cfg.Repos {
			order = append(order, name)
		}
		sort.Strings(order)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s workspace · %s\n\n", cfg.Session, branch)
	b.WriteString(workspaceMapMarker + "\n")
	b.WriteString("> Auto-generated by Pomelo from the project config. Do not hand-edit — it's rewritten on each Claude launch. To change it, edit `pom.yml` / `pom.d`.\n\n")
	b.WriteString("This is a **multi-repo workspace** (a \"virtual monorepo\"): each subdirectory below is one repo's git worktree on this branch. You're rooted at the workspace root, so you can read across all repos.\n\n")

	b.WriteString("## Repos\n")
	for _, name := range order {
		d := cfg.Repos[name]
		if d == nil {
			continue
		}
		alias := d.Alias
		if alias == "" {
			alias = name
		}
		fmt.Fprintf(&b, "- **%s** — `%s/`", alias, name)
		if svcs := repoServiceSummary(d); svcs != "" {
			fmt.Fprintf(&b, " · services: %s", svcs)
		}
		if len(d.Databases) > 0 {
			fmt.Fprintf(&b, " · db: %s", strings.Join(sortedKeys(d.Databases), ", "))
		}
		if len(d.Profiles) > 0 {
			fmt.Fprintf(&b, " · profiles: %s", strings.Join([]string(d.Profiles), ", "))
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")

	b.WriteString("## Working rules\n")
	b.WriteString("- **Read across repos freely, but scope each change to ONE repo / ONE PR.** Don't sprawl one edit pass across repos.\n")
	b.WriteString("- **Only open the repos this task touches** — don't grep every repo blindly; it burns context.\n")
	b.WriteString("- Use the **`pom` MCP** tools (`workspace_info`, `services`, `ports`, `databases`, `commands`, `run_shortcut`, `run_in_env`) for real ports/DB/commands instead of guessing.\n")
	b.WriteString("- " + claude.EnvIsGeneratedNote + "\n")
	b.WriteString("- Each repo may have its own `CLAUDE.md` (loaded when you enter it) — follow it for that repo's conventions.\n")
	return b.String()
}

func repoServiceSummary(d *config.Dir) string {
	if len(d.Services) == 0 {
		return ""
	}
	parts := append([]string(nil), sortedKeys(d.Services)...)
	return strings.Join(parts, ", ")
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
